### ISSUE TITLE
Introducing my own model

### ISSUE THREAD

**Issue by ivancasasola** [miguelzuma/class_scf#1]
I want to introduce a model with a potential with a inverse power law:
V=M ^ (4+n) * phi ^ (-n)
What exactly do I have to change besides the potential and its derivatives?

**Comment by miguelzuma** [comment]
you should include additional parameters to be read by the code.

Note that this repo is not updated: I strongly suggest you work with the public version of CLASS ([https://github.com/lesgourg/class_public](https://github.com/lesgourg/class_public)) which now includes quintessence (and the implementation has been improved).
